#!/usr/bin/env python3

import sys
import os
import re
import signal
import difflib

COLORS = {
    "reset": "\x1b[0m",
    "underline": "\x1b[4m",
    "reverse": "\x1b[7m",
    "plain": "\x1b[22m",
    "red": "\x1b[31m",
    "green": "\x1b[32m",
    "yellow": "\x1b[33m",
    "blue": "\x1b[34m",
    "magenta": "\x1b[35m",
    "cyan": "\x1b[36m",
    "lightred": "\x1b[1;31m",
    "lightgreen": "\x1b[1;32m",
    "lightyellow": "\x1b[1;33m",
    "lightblue": "\x1b[1;34m",
    "lightmagenta": "\x1b[1;35m",
    "lightcyan": "\x1b[1;36m",
}


def colorize(text, start_color, end_color="reset"):
    return COLORS[start_color] + text + COLORS[end_color]


def strsplit(text, width):
    r"""strsplit() splits a given string into two substrings, respecting the
    escape sequences (in a global var COLORS).

    It returns 3-tuple: (first string, second string, number of visible chars
    in the first string).

    If some color was active at the splitting point, then the first string is
    appended with the resetting sequence, and the second string is prefixed
    with all active colors.
    """
    first = ""
    second = ""
    found_colors = []
    chars_cnt = 0
    bytes_cnt = 0
    while text:
        # First of all, check if current string begins with any escape
        # sequence.
        append_len = 0
        for color in COLORS:
            if text.startswith(COLORS[color]):
                if color == "reset":
                    found_colors = []
                else:
                    found_colors.append(color)
                append_len = len(COLORS[color])
                break

        if append_len == 0:
            # Current string does not start with any escape sequence, so,
            # either add one more visible char to the "first" string, or
            # break if that string is already large enough.
            if chars_cnt >= width:
                break
            chars_cnt += 1
            append_len = 1

        first += text[:append_len]
        text = text[append_len:]
        bytes_cnt += append_len

    second = text

    # If the first string has some active colors at the splitting point,
    # reset it and append the same colors to the second string
    if found_colors:
        first += COLORS["reset"]
        for color in found_colors:
            second = COLORS[color] + second

    return (first, second, chars_cnt)


def strtrim(text, width, wrap_char, pad):
    r"""strtrim() trims given string respecting the escape sequences (using
    strsplit), so that if text is larger than width, it's trimmed to have
    width-1 chars plus wrap_char. Additionally, if pad is True, short strings
    are padded with space to have exactly needed width.

    Returns resulting string.
    """
    text, _, tlen = strsplit(text, width + 1)
    if tlen > width:
        text, _, _ = strsplit(text, width - 1)
        text += wrap_char
    elif pad:
        # The string is short enough, but it might need to be padded.
        text = "%s%*s" % (text, width - tlen, "")
    return text


class Hunk(object):
    def __init__(self, hunk_headers, hunk_meta, old_addr, new_addr):
        self._hunk_headers = hunk_headers
        self._hunk_meta = hunk_meta
        self._old_addr = old_addr  # tuple (start, offset)
        self._new_addr = new_addr  # tuple (start, offset)
        self._hunk_list = []  # list of tuple (attr, line)

    def append(self, hunk_line):
        """hunk_line is a 2-element tuple: (attr, text), where attr is:
                '-': old, '+': new, ' ': common
        """
        self._hunk_list.append(hunk_line)

    def mdiff(self):
        r"""The difflib._mdiff() function returns an interator which returns a
        tuple: (from line tuple, to line tuple, boolean flag)

        from/to line tuple -- (line num, line text)
            line num -- integer or None (to indicate a context separation)
            line text -- original line text with following markers inserted:
                '\0+' -- marks start of added text
                '\0-' -- marks start of deleted text
                '\0^' -- marks start of changed text
                '\1' -- marks end of added/deleted/changed text

        boolean flag -- None indicates context separation, True indicates
            either "from" or "to" line contains a change, otherwise False.
        """
        return difflib._mdiff(self._get_old_text(), self._get_new_text())

    def _get_old_text(self):
        return [line for (attr, line) in self._hunk_list if attr != "+"]

    def _get_new_text(self):
        return [line for (attr, line) in self._hunk_list if attr != "-"]

    def is_completed(self):
        old_completed = self._old_addr[1] == len(self._get_old_text())
        new_completed = self._new_addr[1] == len(self._get_new_text())
        return old_completed and new_completed


class UnifiedDiff(object):
    def __init__(self, headers, old_path, new_path, hunks):
        self._headers = headers
        self._old_path = old_path
        self._new_path = new_path
        self._hunks = hunks

    def is_old_path(self, line):
        return line.startswith("--- ")

    def is_new_path(self, line):
        return line.startswith("+++ ")

    def is_hunk_meta(self, line):
        return (
            line.startswith("@@ -")
            and line.find(" @@") >= 8
        )

    def parse_hunk_meta(self, hunk_meta):
        # @@ -3,7 +3,6 @@
        a = hunk_meta.split()[1].split(",")  # -3 7
        if len(a) > 1:
            old_addr = (int(a[0][1:]), int(a[1]))
        else:
            # @@ -1 +1,2 @@
            old_addr = (int(a[0][1:]), 1)

        b = hunk_meta.split()[2].split(",")  # +3 6
        if len(b) > 1:
            new_addr = (int(b[0][1:]), int(b[1]))
        else:
            # @@ -0,0 +1 @@
            new_addr = (int(b[0][1:]), 1)

        return (old_addr, new_addr)

    def parse_hunk_line(self, line):
        return (line[0], line[1:])

    def is_old(self, line):
        """Exclude old path and header line from svn log --diff output, allow
        '----' likely to see in diff from yaml file
        """
        return (
            line.startswith("-")
            and not self.is_old_path(line)
            and not re.match(r"^-{72}$", line.rstrip())
        )

    def is_new(self, line):
        return line.startswith("+") and not self.is_new_path(line)

    def is_common(self, line):
        return line.startswith(" ")

    def is_eof(self, line):
        # \ No newline at end of file
        # \ No newline at end of property
        return line.startswith(r"\ No newline at end of")

    def is_only_in_dir(self, line):
        return line.startswith("Only in ")

    def is_binary_differ(self, line):
        return re.match("^Binary files .* differ$", line.rstrip())


class PatchStream(object):
    def __init__(self, diff_hdl):
        self._diff_hdl = diff_hdl
        self._stream_header_size = 0
        self._stream_header = []

        # Test whether stream is empty by read 1 line
        line = self._diff_hdl.readline()
        if not line:
            self._is_empty = True
        else:
            self._stream_header.append(line)
            self._stream_header_size += 1
            self._is_empty = False

    def is_empty(self):
        return self._is_empty

    def __iter__(self):
        for line in self._stream_header:
            yield line
        try:
            for line in self._diff_hdl:
                yield line
        except RuntimeError:
            return


class DiffParser(object):
    def __init__(self, stream):
        self._type = "unified"
        self._stream = stream

    def get_diff_generator(self):
        """parse all diff lines, construct a list of UnifiedDiff objects"""
        diff = UnifiedDiff([], None, None, [])
        headers = []

        for line in self._stream:
            line = decode(line)

            if diff.is_old_path(line):
                # This is a new diff when current hunk is not yet genreated or
                # is completed.  We yield previous diff if exists and construct
                # a new one for this case.  Otherwise it's acutally an 'old'
                # line starts with '--- '.
                #
                if not diff._hunks or diff._hunks[-1].is_completed():
                    if diff._old_path and diff._new_path and diff._hunks:
                        yield diff
                    diff = UnifiedDiff(headers, line, None, [])
                    headers = []
                else:
                    diff._hunks[-1].append(diff.parse_hunk_line(line))

            elif diff.is_new_path(line) and diff._old_path:
                if not diff._new_path:
                    diff._new_path = line
                else:
                    diff._hunks[-1].append(diff.parse_hunk_line(line))

            elif diff.is_hunk_meta(line):
                hunk_meta = line
                try:
                    old_addr, new_addr = diff.parse_hunk_meta(hunk_meta)
                except (IndexError, ValueError):
                    raise RuntimeError("invalid hunk meta: %s" % hunk_meta)
                hunk = Hunk(headers, hunk_meta, old_addr, new_addr)
                headers = []
                diff._hunks.append(hunk)

            elif (
                diff._hunks
                and not headers
                and (diff.is_old(line) or diff.is_new(line) or diff.is_common(line))
            ):
                diff._hunks[-1].append(diff.parse_hunk_line(line))

            elif diff.is_eof(line):
                # ignore
                pass

            elif diff.is_only_in_dir(line) or diff.is_binary_differ(line):
                # 'Only in foo:' and 'Binary files ... differ' are considered
                # as separate diffs, so yield current diff, then this line
                #
                if diff._old_path and diff._new_path and diff._hunks:
                    # Current diff is comppletely constructed
                    yield diff
                headers.append(line)
                yield UnifiedDiff(headers, "", "", [])
                headers = []
                diff = UnifiedDiff([], None, None, [])

            else:
                # All other non-recognized lines are considered as headers or
                # hunk headers respectively
                #
                headers.append(line)

        # Validate and yield the last patch set if it is not yielded yet
        if diff._old_path:
            assert diff._new_path is not None
            if diff._hunks:
                assert len(diff._hunks[-1]._hunk_meta) > 0
                assert len(diff._hunks[-1]._hunk_list) > 0
            yield diff

        if headers:
            # Tolerate dangling headers, just yield a UnifiedDiff object with
            # only header lines
            #
            yield UnifiedDiff(headers, "", "", [])


class DiffMarker(object):
    def __init__(self, side_by_side=False, width=0, tab_width=8, wrap=False):
        self._side_by_side = side_by_side
        self._width = width
        self._tab_width = tab_width
        self._wrap = wrap

    def markup(self, diff):
        """Returns a generator"""
        for line in self._markup_side_by_side(diff):
            yield line

    def _markup_side_by_side(self, diff):
        """Returns a generator"""

        def _normalize(line):
            return (
                line.replace("\t", " " * self._tab_width)
                .replace("\n", "")
                .replace("\r", "")
            )

        def _fit_with_marker_mix(text):
            """Wrap input text which contains mdiff tags, markup at the
            meantime
            """
            out = [COLORS["plain"]]

            while text:
                if text.startswith("\x00-"):
                    out.append(COLORS["reverse"] + COLORS["red"])
                    text = text[2:]
                elif text.startswith("\x00+"):
                    out.append(COLORS["reverse"] + COLORS["green"])
                    text = text[2:]
                elif text.startswith("\x00^"):
                    out.append(COLORS["reverse"] + COLORS["yellow"])
                    text = text[2:]
                elif text.startswith("\x01"):
                    if len(text) > 1:
                        out.append(COLORS["reset"] + COLORS["plain"])
                    text = text[1:]
                else:
                    # FIXME: utf-8 wchar might break the rule here, e.g.
                    # u'\u554a' takes double width of a single letter, also
                    # this depends on your terminal font.  I guess audience of
                    # this tool never put that kind of symbol in their code :-)
                    #
                    out.append(text[0])
                    text = text[1:]

            out.append(COLORS["reset"])

            return "".join(out)

        # Set up number width, note last hunk might be empty
        try:
            (start, offset) = diff._hunks[-1]._old_addr
            max1 = start + offset - 1
            (start, offset) = diff._hunks[-1]._new_addr
            max2 = start + offset - 1
        except IndexError:
            max1 = max2 = 0
        num_width = max(len(str(max1)), len(str(max2)))

        # Set up line width
        width = self._width
        if width <= 0:
            # Autodetection of text width according to terminal size
            try:
                # Each line is like 'nnn TEXT nnn TEXT\n', so width is half of
                # [terminal size minus the line number columns and 3 separating
                # spaces
                #
                width = (terminal_size()[0] - num_width * 2 - 3) // 2
            except Exception:
                # If terminal detection failed, set back to default
                width = 80

        # Setup lineno and line format
        left_num_fmt = colorize("%%(left_num)%ds" % num_width, "yellow")
        right_num_fmt = colorize("%%(right_num)%ds" % num_width, "yellow")
        line_fmt = (
            left_num_fmt
            + " %(left)s "
            + COLORS["reset"]
            + right_num_fmt
            + " %(right)s\n"
        )

        # yield header, old path and new path
        for line in diff._headers:
            yield self._markup_header(line)
        yield self._markup_old_path(diff._old_path)
        yield self._markup_new_path(diff._new_path)

        # yield hunks
        for hunk in diff._hunks:
            for hunk_header in hunk._hunk_headers:
                yield self._markup_hunk_header(hunk_header)
            yield self._markup_hunk_meta(hunk._hunk_meta)
            for old, new, changed in hunk.mdiff():
                if old[0]:
                    left_num = str(hunk._old_addr[0] + int(old[0]) - 1)
                else:
                    left_num = " "

                if new[0]:
                    right_num = str(hunk._new_addr[0] + int(new[0]) - 1)
                else:
                    right_num = " "

                left = _normalize(old[1])
                right = _normalize(new[1])

                if changed:
                    if not old[0]:
                        left = ""
                        right = right.rstrip("\x01")
                        if right.startswith("\x00+"):
                            right = right[2:]
                        right = self._markup_new(right)
                    elif not new[0]:
                        left = left.rstrip("\x01")
                        if left.startswith("\x00-"):
                            left = left[2:]
                        left = self._markup_old(left)
                        right = ""
                    else:
                        left = _fit_with_marker_mix(left)
                        right = _fit_with_marker_mix(right)
                else:
                    left = self._markup_common(left)
                    right = self._markup_common(right)

                if self._wrap:
                    # Need to wrap long lines, so here we'll iterate,
                    # shaving off `width` chars from both left and right
                    # strings, until both are empty. Also, line number needs to
                    # be printed only for the first part.
                    lncur = left_num
                    rncur = right_num
                    while left or right:
                        # Split both left and right lines, preserving escaping
                        # sequences correctly.
                        lcur, left, llen = strsplit(left, width)
                        rcur, right, rlen = strsplit(right, width)

                        # Pad left line with spaces if needed
                        if llen < width:
                            lcur = "%s%*s" % (lcur, width - llen, "")

                        yield line_fmt % {
                            "left_num": lncur,
                            "left": lcur,
                            "right_num": rncur,
                            "right": rcur,
                        }

                        # Clean line numbers for further iterations
                        lncur = ""
                        rncur = ""
                else:
                    # Don't need to wrap long lines; instead, a trailing '>'
                    # char needs to be appended.
                    wrap_char = colorize(">", "lightmagenta")
                    left = strtrim(left, width, wrap_char, len(right) > 0)
                    right = strtrim(right, width, wrap_char, False)

                    yield line_fmt % {
                        "left_num": left_num,
                        "left": left,
                        "right_num": right_num,
                        "right": right,
                    }

    def _markup_header(self, line):
        return colorize(line, "cyan")

    def _markup_old_path(self, line):
        return colorize(line, "yellow")

    def _markup_new_path(self, line):
        return colorize(line, "yellow")

    def _markup_hunk_header(self, line):
        return colorize(line, "lightcyan")

    def _markup_hunk_meta(self, line):
        return colorize(line, "lightblue")

    def _markup_common(self, line):
        return colorize(line, "reset")

    def _markup_old(self, line):
        return colorize(line, "lightred")

    def _markup_new(self, line):
        return colorize(line, "green")


def decode(line):
    """Decode UTF-8 if necessary."""
    if isinstance(line, str):
        return line

    for encoding in ["utf-8", "latin1"]:
        try:
            return line.decode(encoding)
        except UnicodeDecodeError:
            pass

    return "*** ydiff: undecodable bytes ***\n"


def terminal_size():
    """Returns terminal size. Taken from https://gist.github.com/marsam/7268750
    but removed win32 support which depends on 3rd party extension.
    """
    width, height = None, None
    try:
        import struct
        import fcntl
        import termios

        s = struct.pack("HHHH", 0, 0, 0, 0)
        x = fcntl.ioctl(1, termios.TIOCGWINSZ, s)
        height, width = struct.unpack("HHHH", x)[0:2]
    except (IOError, AttributeError):
        pass
    return width, height


def main():
    signal.signal(signal.SIGPIPE, signal.SIG_DFL)
    signal.signal(signal.SIGINT, signal.SIG_DFL)

    from optparse import OptionParser, BadOptionError, AmbiguousOptionError

    class PassThroughOptionParser(OptionParser):
        """Stop parsing on first unknown option (e.g. --cached, -U10) and pass
        them down.  Note the `opt_str` in exception object does not give us
        chance to take the full option back, e.g. for '-U10' it will only
        contain '-U' and the '10' part will be lost.  Ref: http://goo.gl/IqY4A
        (on stackoverflow).  My hack is to try parse and insert a '--' in place
        and parse again.  Let me know if someone has better solution.
        """

        def _process_args(self, largs, rargs, values):
            left = largs[:]
            right = rargs[:]
            try:
                OptionParser._process_args(self, left, right, values)
            except (BadOptionError, AmbiguousOptionError):
                parsed_num = len(rargs) - len(right) - 1
                rargs.insert(parsed_num, "--")
            OptionParser._process_args(self, largs, rargs, values)

    usage = """%prog [options] [file|dir ...]"""
    parser = PassThroughOptionParser(usage=usage)
    parser.add_option(
        "-s", "--side-by-side", action="store_true", help="enable side-by-side mode"
    )
    parser.add_option(
        "-w",
        "--width",
        type="int",
        default=80,
        metavar="N",
        help="set text width for side-by-side mode, 0 for auto detection, "
        "default is 80",
    )
    parser.add_option(
        "-c",
        "--color",
        default="auto",
        metavar="M",
        help="""colorize mode 'auto' (default), 'always', or 'never'""",
    )
    parser.add_option(
        "-t",
        "--tab-width",
        type="int",
        default=8,
        metavar="N",
        help="""convert tab characters to this many spcaes (default: 8)""",
    )
    parser.add_option(
        "", "--wrap", action="store_true", help="wrap long lines in side-by-side view"
    )

    # Place possible options defined in YDIFF_OPTIONS at the beginning of argv
    ydiff_opts = [x for x in os.getenv("YDIFF_OPTIONS", "").split(" ") if x]

    opts, args = parser.parse_args(ydiff_opts + sys.argv[1:])

    stream = PatchStream(sys.stdin)

    if stream.is_empty():
        return 0

    byte_output = sys.stdout.buffer if hasattr(sys.stdout, "buffer") else sys.stdout

    diffs = DiffParser(stream).get_diff_generator()
    for diff in diffs:
        marker = DiffMarker(
            side_by_side=opts.side_by_side,
            width=opts.width,
            tab_width=opts.tab_width,
            wrap=opts.wrap,
        )
    color_diff = marker.markup(diff)
    for line in color_diff:
        byte_output.write(line.encode("utf-8"))

    return 0


if __name__ == "__main__":
    sys.exit(main())
